FROM alpine
MAINTAINER KK512
ARG NAME
ARG AGE=12
ENV ENV_NAME=${NAME} \
    ENV_AGE=${AGE}

#https://vsupalov.com/docker-arg-env-variable-guide/

#docker build -f Dockerfile.ENVS -t e_args --build-arg NAME=KAR512 --build-arg AGE=34 .
#docker run -e ENV_NAME=K.KAR512 -e AGE=24 -e GRADE=D -it --rm e_args
